### ISSUE TITLE
Can't make it work!

### ISSUE THREAD

**Issue by xenoflot** [JoseluGames/ParticleGenerator#4]
http://i.imgur.com/sr7rVrc.png

Perhaps I'm derping... I've tried a couple of different effects. I've tried a few different positions with x y and z. I've tried with and without redstone signal applied. I've tried with an RF powercell next to it. I can't get the block to do anything. Not sure if the red dots in the middle of the texture are supposed to light up when redstone is applied, but they're not.

pg 1.10.2-0.1.2-hotfix

Cheers!

**Comment by JoseluGames** [comment]
Thank you for all the feedback! At this moment I can't fix the other issues but I can tell you that the coords are absolute, not relative to the block, so the particles are spawning at 0, -20, 0

**Comment by xenoflot** [comment]
> absolute, not relative

Hah! OK, that explains that :-) I'll close this and go back to adding feedback :) Out of curiosity, what's your schedule for returning to the project? Days? Weeks? Months? No pressure, just curious.

**Comment by JoseluGames** [comment]
I don't have any schedule, I work on it whenever I can and I have things to do, like fixing things hahaha

**Comment by xenoflot** [comment]
Ah gotcha! The way you phrased it made me think you were tied up with university or something. At your leisure, good sir!
